#!/usr/bin/env bash
# ck-code guard — AUTO-GENERATED by ck-bootstrap. DO NOT EDIT BY HAND.
# ck-code-guard: 1
#
# Committed with the repo so it runs on ANY clone, including one on a machine that has
# never installed ck-code. This project stores its plan under the ck-code layout
# (tasks/VERSION.md), and every command that reads or writes that state ships with the
# plugin — so a session without it can only improvise around the gap.
#
# Best-effort by design: never fails, never blocks, emits one JSON line or nothing.
cd "${CLAUDE_PROJECT_DIR:-.}" 2>/dev/null || exit 0

# Not a ck-code project → not this guard's business.
[ -f tasks/VERSION.md ] || exit 0

CFG="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
installed=no

# Cheapest first: the plugin puts bin/ on PATH whenever it is live.
command -v ck-index >/dev/null 2>&1 && installed=yes

# A copy vendored into the repo by an older ck-code still provides the commands.
[ "$installed" = no ] && [ -f .claude/skills/ck-code/.claude-plugin/plugin.json ] && installed=yes

# Marketplace install, whatever version and marketplace it came from.
if [ "$installed" = no ]; then
  for p in "$CFG"/plugins/cache/*/ck-code/*/.claude-plugin/plugin.json; do
    [ -f "$p" ] && { installed=yes; break; }
  done
fi
[ "$installed" = no ] && grep -q '"ck-code@' "$CFG/plugins/installed_plugins.json" 2>/dev/null && installed=yes

[ "$installed" = yes ] && exit 0

printf '%s\n' '{"hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"⛔ ck-code is REQUIRED in this project and is not installed. This repo keeps its plan, stories and architecture in the ck-code layout (tasks/VERSION.md), and every command that reads or writes that state ships with the plugin. STOP before doing anything else here: do not plan, implement, commit, edit tasks/ or docs/architecture/, and never improvise a stand-in for a /ck-code:* command. Give the user these commands and wait: /plugin marketplace add ckandrinirina/ck-code — then /plugin install ck-code@ck-marketplace — then restart the session."}}'
